#' Launch the Shiny app
#'
#' @param playlist data.frame: a playlist as returned by \code{\link[ovideo]{ov_video_playlist}}
#' @param video_server string: the method used to serve local video files, either "lighttpd" or "servr". If it is \code{NULL}, no local server will be started and only remote video files can be used
#' @param launch_browser logical: if \code{TRUE}, launch the app in the system's default web browser (passed to \code{\link[shiny]{runApp}}'s \code{launch.browser} parameter)
#' @param mobile logical: if \code{TRUE}, launch the app's mobile UI version
#' @param host string: shiny host. Defaults to "127.0.0.1"
#' @param ... : additional parameters passed to the UI and server functions
#'
#' @examples
#' \dontrun{
#'  ## read example playlist
#'  ply <- ovp_example_playlist(1)
#'
#'  ## start shiny app
#'  ovp_shiny(playlist = ply, video_server = "servr")
#' }
#' @export
ovp_shiny <- function(playlist, video_server = NULL, launch_browser = TRUE, mobile = FALSE, host = "127.0.0.1",...) {
    assert_that(is.flag(launch_browser), !is.na(launch_browser))
    assert_that(is.flag(mobile), !is.na(mobile))
    assert_that(is.data.frame(playlist))
    if (!all(c("video_src", "start_time", "duration", "type") %in% names(playlist))) stop("playlist does not appear to be a playlist as generated by ovideo::ov_video_playlist")
    if (is.null(video_server)) video_server <- "none"
    assert_that(is.string(video_server) || is.function(video_server))
    if (is.string(video_server)) video_server <- match.arg(tolower(video_server), c("lighttpd", "servr", "none"))
    ## sort out the video server
    if (video_server == "none") {
        vsrv <- list(method = video_server, url = NULL, dir = NULL)
    } else {
        vsrv <- ovp_video_server(method = video_server, host = host)
        onStop(function() try({ vsrv$cleanup_fun() }, silent = TRUE))
    }
    app_data <- c(list(playlist = playlist, video_serve_method = vsrv$method, video_server_dir = vsrv$dir, video_server_url = vsrv$url), list(...))
    this_app <- list(ui = if (mobile) ovp_shiny_mobile_ui(app_data = app_data) else ovp_shiny_ui(app_data = app_data),
                     server = ovp_shiny_server(app_data = app_data))
    shiny::runApp(this_app, display.mode = "normal", launch.browser = launch_browser, host = host)
}
